### ISSUE TITLE
Potential ERC20Mock issue on goerli

### ISSUE THREAD

**Issue by scglenn** [Layr-Labs/eigenlayer-avs-playgrounds#7]
I've been experimenting with the avs playground and some of the contracts deployed on goerli.

Maybe i'm missing something, but the deployed ERC20Mock listed in this json doesn't seem correctly deployed.
[eigenlayer_deployment_output.json]( https://github.com/Layr-Labs/eigenlayer-avs-playgrounds/blob/alpha/script/output/5/eigenlayer_deployment_output.json
)

I expected the creator to have a balance for this mock token but they dont.
[See mint on construction](https://github.com/Layr-Labs/eigenlayer-contracts/blob/a793a4193e6273200625d13e9d9c2d8ea2b4cb2d/src/test/mocks/ERC20Mock.sol#L47C11-L47C11)

![image](https://github.com/Layr-Labs/eigenlayer-avs-playgrounds/assets/13244114/4053e785-e482-4047-bc21-64c42cd464d2)

ERC20Mock Address: https://goerli.etherscan.io/address/0x0f2961a3ded5806c6eeb3159fd2f433edf7e6fee

**Comment by samlaf** [comment]
Sorry about that confusion. The ERC20Mock deployed is actually [this contract](https://github.com/Layr-Labs/eigenlayer-avs-playgrounds/blob/alpha/src/test/mocks/ERC20Mock.sol). It doesn't mint on construction, but instead has a permissionless [mint](https://github.com/Layr-Labs/eigenlayer-avs-playgrounds/blob/a3660806f6bd6f063b302c7ad1c32b4b48940455/src/test/mocks/ERC20Mock.sol#L60) function that anyone can call.

This is in fact what we do in the staker script, which calls this [util function](https://github.com/Layr-Labs/eigenlayer-avs-playgrounds/blob/a3660806f6bd6f063b302c7ad1c32b4b48940455/script/utils/Utils.sol#L22).
